[build]
  command = "yarn build --configuration=production --base-href /"
  publish = "dist/reedu-home-v2"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.3"
  YARN_VERSION = "1.22.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
